#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ActionsContentViewExample.Resource", IsApplication=true)]

namespace ActionsContentViewExample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int effect_alpha_content = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int effect_bounce_content = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int effect_duration_content = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int effect_overshot_content = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int effect_paralax_actions = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int effect_replace_actions = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int effect_replace_content = 2130968582;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080006
			public const int actions_icons = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int actions_links = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int actions_names = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int bounce_effect = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int effect_layouts = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int effects_actions_html = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int effects_content_html = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int effects_name = 2131230720;
			
			// aapt resource value: 0x7f080010
			public const int fade_max_value_strings = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int fade_max_value_values = 2131230737;
			
			// aapt resource value: 0x7f08000e
			public const int fade_types = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int fade_types_values = 2131230735;
			
			// aapt resource value: 0x7f080014
			public const int fling_duration_strings = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int fling_duration_values = 2131230741;
			
			// aapt resource value: 0x7f080005
			public const int overshot_effect = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int spacing_types = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int spacing_types_short = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int spacing_types_values = 2131230731;
			
			// aapt resource value: 0x7f080012
			public const int swiping_types = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int swiping_types_values = 2131230739;
			
			// aapt resource value: 0x7f08000c
			public const int width_strings = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int width_values = 2131230733;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int actions_layout = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int actions_spacing = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int content_layout = 2130771975;
			
			// aapt resource value: 0x7f01000d
			public const int effect_actions = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int effect_content = 2130771982;
			
			// aapt resource value: 0x7f010002
			public const int effects = 2130771970;
			
			// aapt resource value: 0x7f01000f
			public const int effects_interpolator = 2130771983;
			
			// aapt resource value: 0x7f01000a
			public const int fade_max_value = 2130771978;
			
			// aapt resource value: 0x7f010001
			public const int fade_type = 2130771969;
			
			// aapt resource value: 0x7f01000b
			public const int fling_duration = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int shadow_drawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadow_width = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int spacing = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int spacing_type = 2130771968;
			
			// aapt resource value: 0x7f01000c
			public const int swiping_edge_width = 2130771980;
			
			// aapt resource value: 0x7f010003
			public const int swiping_type = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0a0000
			public const int default_pref_show_shadow = 2131361792;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090003
			public const int actions_bg = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int actions_divider = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int bottom_bar_bg = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int bottom_bar_text = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int divider = 2131296256;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060007
			public const int actions_spacing = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int default_actionscontentview_actions_spacing = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int default_actionscontentview_spacing = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int default_actionscontentview_swiping_edge_width = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int default_pref_shadow_width = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int default_pref_swiping_edge_width = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int divider_large_size = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int divider_size = 2131099653;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_code = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_about = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_effects = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_settings = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_link_dropbox = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_link_evernote = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_link_facebook = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_link_github = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_link_google_plus = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_link_lastfm = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_link_linkedin = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_link_skype = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_link_stackoverflow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_link_twitter = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_link_vk = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_link_yandex = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_link_youtube = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_menu_moreoverflow_normal_holo_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int item_background_holo_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int list_focused_holo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int list_longpressed_holo = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int list_pressed_holo_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int list_selector_background_transition_holo_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int list_selector_disabled_holo_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int progress_bg_holo_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int progress_horizontal_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int progress_primary_holo_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int progress_secondary_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int shadow = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int actions = 2131034115;
			
			// aapt resource value: 0x7f050013
			public const int actionsContentView = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int actions_html = 2131034134;
			
			// aapt resource value: 0x7f050001
			public const int actions_width = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int all = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int both = 2131034117;
			
			// aapt resource value: 0x7f050019
			public const int bottomBar = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int content = 2131034116;
			
			// aapt resource value: 0x7f050018
			public const int content_html = 2131034136;
			
			// aapt resource value: 0x7f050011
			public const int divider = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int edge = 2131034126;
			
			// aapt resource value: 0x7f050015
			public const int effect_actions_layout = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int effect_content_layout = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int effect_name = 2131034132;
			
			// aapt resource value: 0x7f05000b
			public const int fling = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int fling_closing = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int fling_opening = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int full = 2131034125;
			
			// aapt resource value: 0x7f05001a
			public const int mainButton = 2131034138;
			
			// aapt resource value: 0x7f050002
			public const int none = 2131034114;
			
			// aapt resource value: 0x7f05000f
			public const int play = 2131034127;
			
			// aapt resource value: 0x7f05001e
			public const int prefFadeMaxValue = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int prefFadeMaxValueValue = 2131034143;
			
			// aapt resource value: 0x7f05001c
			public const int prefFadeType = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int prefFadeTypeValue = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int prefFlingDuration = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int prefFlingDurationValue = 2131034145;
			
			// aapt resource value: 0x7f050024
			public const int prefShadowWidth = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int prefShadowWidthValue = 2131034149;
			
			// aapt resource value: 0x7f050022
			public const int prefShowShadow = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int prefShowShadowValue = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public const int prefSpacingActionsWidth = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int prefSpacingActionsWidthValue = 2131034156;
			
			// aapt resource value: 0x7f050026
			public const int prefSpacingType = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int prefSpacingTypeValue = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int prefSpacingWidth = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int prefSpacingWidthAdditionalValue = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int prefSpacingWidthValue = 2131034154;
			
			// aapt resource value: 0x7f05002f
			public const int prefSwipingEdgeWidth = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int prefSwipingEdgeWidthValue = 2131034160;
			
			// aapt resource value: 0x7f05002d
			public const int prefSwipingType = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int prefSwipingTypeValue = 2131034158;
			
			// aapt resource value: 0x7f050032
			public const int progress = 2131034162;
			
			// aapt resource value: 0x7f050000
			public const int right_offset = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int scroll = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int scroll_closing = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int scroll_opening = 2131034118;
			
			// aapt resource value: 0x7f05001b
			public const int sourceCodeButton = 2131034139;
			
			// aapt resource value: 0x7f050012
			public const int title = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int tutorial = 2131034128;
			
			// aapt resource value: 0x7f050031
			public const int webview = 2131034161;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int default_actionscontentview_fade_max_value = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_actionscontentview_fling_duration = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_pref_fade_max_value = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int default_pref_fling_delay = 2131165187;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int action_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int actions = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int category_list_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int content = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int effect_actions = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int effect_alpha = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int effect_bounce = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int effect_content = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int effect_duration = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int effect_overshot = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int effect_parallax = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int effect_replace = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int example = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int pref_fade = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int pref_other = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int pref_shadow = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int pref_spacing = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int pref_swiping = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int sandbox = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int webview = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b000a
			public const int about_details = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int about_play = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int about_tutorial = 2131427340;
			
			// aapt resource value: 0x7f0b001d
			public const int action_about = 2131427357;
			
			// aapt resource value: 0x7f0b0020
			public const int action_bookmarks = 2131427360;
			
			// aapt resource value: 0x7f0b001f
			public const int action_effects = 2131427359;
			
			// aapt resource value: 0x7f0b001e
			public const int action_sandbox = 2131427358;
			
			// aapt resource value: 0x7f0b001c
			public const int action_settings = 2131427356;
			
			// aapt resource value: 0x7f0b0008
			public const int app_name = 2131427336;
			
			// aapt resource value: 0x7f0b0023
			public const int effect_alpha = 2131427363;
			
			// aapt resource value: 0x7f0b0007
			public const int effect_alpha_content_html = 2131427335;
			
			// aapt resource value: 0x7f0b0025
			public const int effect_bounce = 2131427365;
			
			// aapt resource value: 0x7f0b0006
			public const int effect_bounce_content_html = 2131427334;
			
			// aapt resource value: 0x7f0b0027
			public const int effect_content_actions_xml = 2131427367;
			
			// aapt resource value: 0x7f0b0028
			public const int effect_content_content_xml = 2131427368;
			
			// aapt resource value: 0x7f0b0024
			public const int effect_duration = 2131427364;
			
			// aapt resource value: 0x7f0b0005
			public const int effect_duration_content_html = 2131427333;
			
			// aapt resource value: 0x7f0b0026
			public const int effect_overshot = 2131427366;
			
			// aapt resource value: 0x7f0b0004
			public const int effect_overshot_content_html = 2131427332;
			
			// aapt resource value: 0x7f0b0021
			public const int effect_parallax = 2131427361;
			
			// aapt resource value: 0x7f0b0001
			public const int effect_parallax_actions_html = 2131427329;
			
			// aapt resource value: 0x7f0b0022
			public const int effect_replace = 2131427362;
			
			// aapt resource value: 0x7f0b0002
			public const int effect_replace_actions_html = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int effect_replace_content_html = 2131427331;
			
			// aapt resource value: 0x7f0b0009
			public const int link_to_sources = 2131427337;
			
			// aapt resource value: 0x7f0b0014
			public const int pref_fade = 2131427348;
			
			// aapt resource value: 0x7f0b0016
			public const int pref_fade_max_value = 2131427350;
			
			// aapt resource value: 0x7f0b0015
			public const int pref_fade_type = 2131427349;
			
			// aapt resource value: 0x7f0b001a
			public const int pref_other = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int pref_other_fling_duration = 2131427355;
			
			// aapt resource value: 0x7f0b0011
			public const int pref_shadow = 2131427345;
			
			// aapt resource value: 0x7f0b0013
			public const int pref_shadow_width = 2131427347;
			
			// aapt resource value: 0x7f0b0012
			public const int pref_show_shadow = 2131427346;
			
			// aapt resource value: 0x7f0b000d
			public const int pref_spacing = 2131427341;
			
			// aapt resource value: 0x7f0b0010
			public const int pref_spacing_actions = 2131427344;
			
			// aapt resource value: 0x7f0b000e
			public const int pref_spacing_type = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int pref_spacing_width = 2131427343;
			
			// aapt resource value: 0x7f0b0017
			public const int pref_swiping = 2131427351;
			
			// aapt resource value: 0x7f0b0019
			public const int pref_swiping_edge_width = 2131427353;
			
			// aapt resource value: 0x7f0b0018
			public const int pref_swiping_type = 2131427352;
			
			// aapt resource value: 0x7f0b0000
			public const int sources_link = 2131427328;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0c0000
			public const int AppTheme = 2131492864;
			
			// aapt resource value: 0x7f0c0002
			public const int HeaderText = 2131492866;
			
			// aapt resource value: 0x7f0c0001
			public const int HoloButton_Borderless = 2131492865;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionsContentView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 6
			public const int ActionsContentView_actions_layout = 6;
			
			// aapt resource value: 5
			public const int ActionsContentView_actions_spacing = 5;
			
			// aapt resource value: 7
			public const int ActionsContentView_content_layout = 7;
			
			// aapt resource value: 13
			public const int ActionsContentView_effect_actions = 13;
			
			// aapt resource value: 14
			public const int ActionsContentView_effect_content = 14;
			
			// aapt resource value: 2
			public const int ActionsContentView_effects = 2;
			
			// aapt resource value: 15
			public const int ActionsContentView_effects_interpolator = 15;
			
			// aapt resource value: 10
			public const int ActionsContentView_fade_max_value = 10;
			
			// aapt resource value: 1
			public const int ActionsContentView_fade_type = 1;
			
			// aapt resource value: 11
			public const int ActionsContentView_fling_duration = 11;
			
			// aapt resource value: 8
			public const int ActionsContentView_shadow_drawable = 8;
			
			// aapt resource value: 9
			public const int ActionsContentView_shadow_width = 9;
			
			// aapt resource value: 4
			public const int ActionsContentView_spacing = 4;
			
			// aapt resource value: 0
			public const int ActionsContentView_spacing_type = 0;
			
			// aapt resource value: 12
			public const int ActionsContentView_swiping_edge_width = 12;
			
			// aapt resource value: 3
			public const int ActionsContentView_swiping_type = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
