#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NWTBible.Resource", IsApplication=true)]

namespace NWTBible
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0c0000
			public const int colors = 2131492864;
			
			// aapt resource value: 0x7f0c0005
			public const int donateType = 2131492869;
			
			// aapt resource value: 0x7f0c0001
			public const int planets = 2131492865;
			
			// aapt resource value: 0x7f0c0003
			public const int readerFontSizes = 2131492867;
			
			// aapt resource value: 0x7f0c0004
			public const int readerType = 2131492868;
			
			// aapt resource value: 0x7f0c0002
			public const int themeStyles = 2131492866;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01001c
			public const int actionBarDivider = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int actionBarItemBackground = 2130771997;
			
			// aapt resource value: 0x7f01001b
			public const int actionBarSize = 2130771995;
			
			// aapt resource value: 0x7f010019
			public const int actionBarSplitStyle = 2130771993;
			
			// aapt resource value: 0x7f010018
			public const int actionBarStyle = 2130771992;
			
			// aapt resource value: 0x7f010015
			public const int actionBarTabBarStyle = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int actionBarTabStyle = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int actionBarTabTextStyle = 2130771990;
			
			// aapt resource value: 0x7f01001a
			public const int actionBarWidgetTheme = 2130771994;
			
			// aapt resource value: 0x7f010048
			public const int actionButtonStyle = 2130772040;
			
			// aapt resource value: 0x7f010047
			public const int actionDropDownStyle = 2130772039;
			
			// aapt resource value: 0x7f01001e
			public const int actionMenuTextAppearance = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int actionMenuTextColor = 2130771999;
			
			// aapt resource value: 0x7f010022
			public const int actionModeBackground = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int actionModeCloseButtonStyle = 2130772001;
			
			// aapt resource value: 0x7f010024
			public const int actionModeCloseDrawable = 2130772004;
			
			// aapt resource value: 0x7f010026
			public const int actionModePopupWindowStyle = 2130772006;
			
			// aapt resource value: 0x7f010025
			public const int actionModeShareDrawable = 2130772005;
			
			// aapt resource value: 0x7f010023
			public const int actionModeSplitBackground = 2130772003;
			
			// aapt resource value: 0x7f010020
			public const int actionModeStyle = 2130772000;
			
			// aapt resource value: 0x7f010017
			public const int actionOverflowButtonStyle = 2130771991;
			
			// aapt resource value: 0x7f01004d
			public const int actionSpinnerItemStyle = 2130772045;
			
			// aapt resource value: 0x7f010055
			public const int activatedBackgroundIndicator = 2130772053;
			
			// aapt resource value: 0x7f010054
			public const int activityChooserViewStyle = 2130772052;
			
			// aapt resource value: 0x7f010010
			public const int background = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int backgroundSplit = 2130771985;
			
			// aapt resource value: 0x7f01005c
			public const int backgroundStacked = 2130772060;
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f010027
			public const int buttonStyleSmall = 2130772007;
			
			// aapt resource value: 0x7f010073
			public const int column_count = 2130772083;
			
			// aapt resource value: 0x7f010072
			public const int column_width = 2130772082;
			
			// aapt resource value: 0x7f01005d
			public const int customNavigationLayout = 2130772061;
			
			// aapt resource value: 0x7f010057
			public const int displayOptions = 2130772055;
			
			// aapt resource value: 0x7f010013
			public const int divider = 2130771987;
			
			// aapt resource value: 0x7f010046
			public const int dividerVertical = 2130772038;
			
			// aapt resource value: 0x7f01004a
			public const int dropDownListViewStyle = 2130772042;
			
			// aapt resource value: 0x7f01004c
			public const int dropdownListPreferredItemHeight = 2130772044;
			
			// aapt resource value: 0x7f01006c
			public const int expandActivityOverflowButtonDrawable = 2130772076;
			
			// aapt resource value: 0x7f01000b
			public const int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010066
			public const int headerBackground = 2130772070;
			
			// aapt resource value: 0x7f010012
			public const int height = 2130771986;
			
			// aapt resource value: 0x7f010049
			public const int homeAsUpIndicator = 2130772041;
			
			// aapt resource value: 0x7f01005e
			public const int homeLayout = 2130772062;
			
			// aapt resource value: 0x7f010064
			public const int horizontalDivider = 2130772068;
			
			// aapt resource value: 0x7f010070
			public const int horizontal_spacing = 2130772080;
			
			// aapt resource value: 0x7f01005a
			public const int icon = 2130772058;
			
			// aapt resource value: 0x7f01006d
			public const int iconifiedByDefault = 2130772077;
			
			// aapt resource value: 0x7f010060
			public const int indeterminateProgressStyle = 2130772064;
			
			// aapt resource value: 0x7f01006b
			public const int initialActivityCount = 2130772075;
			
			// aapt resource value: 0x7f010067
			public const int itemBackground = 2130772071;
			
			// aapt resource value: 0x7f010069
			public const int itemIconDisabledAlpha = 2130772073;
			
			// aapt resource value: 0x7f010062
			public const int itemPadding = 2130772066;
			
			// aapt resource value: 0x7f010063
			public const int itemTextAppearance = 2130772067;
			
			// aapt resource value: 0x7f010053
			public const int listPopupWindowStyle = 2130772051;
			
			// aapt resource value: 0x7f010040
			public const int listPreferredItemHeightSmall = 2130772032;
			
			// aapt resource value: 0x7f010041
			public const int listPreferredItemPaddingLeft = 2130772033;
			
			// aapt resource value: 0x7f010042
			public const int listPreferredItemPaddingRight = 2130772034;
			
			// aapt resource value: 0x7f01005b
			public const int logo = 2130772059;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f010056
			public const int navigationMode = 2130772054;
			
			// aapt resource value: 0x7f01004b
			public const int popupMenuStyle = 2130772043;
			
			// aapt resource value: 0x7f01006a
			public const int preserveIconSpacing = 2130772074;
			
			// aapt resource value: 0x7f010061
			public const int progressBarPadding = 2130772065;
			
			// aapt resource value: 0x7f01005f
			public const int progressBarStyle = 2130772063;
			
			// aapt resource value: 0x7f01006e
			public const int queryHint = 2130772078;
			
			// aapt resource value: 0x7f010032
			public const int searchAutoCompleteTextView = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int searchDropdownBackground = 2130772019;
			
			// aapt resource value: 0x7f01003d
			public const int searchResultListItemHeight = 2130772029;
			
			// aapt resource value: 0x7f010034
			public const int searchViewCloseIcon = 2130772020;
			
			// aapt resource value: 0x7f010038
			public const int searchViewEditQuery = 2130772024;
			
			// aapt resource value: 0x7f010039
			public const int searchViewEditQueryBackground = 2130772025;
			
			// aapt resource value: 0x7f010035
			public const int searchViewGoIcon = 2130772021;
			
			// aapt resource value: 0x7f010036
			public const int searchViewSearchIcon = 2130772022;
			
			// aapt resource value: 0x7f01003a
			public const int searchViewTextField = 2130772026;
			
			// aapt resource value: 0x7f01003b
			public const int searchViewTextFieldRight = 2130772027;
			
			// aapt resource value: 0x7f010037
			public const int searchViewVoiceIcon = 2130772023;
			
			// aapt resource value: 0x7f010028
			public const int selectableItemBackground = 2130772008;
			
			// aapt resource value: 0x7f01000d
			public const int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010031
			public const int spinnerDropDownItemStyle = 2130772017;
			
			// aapt resource value: 0x7f010030
			public const int spinnerItemStyle = 2130772016;
			
			// aapt resource value: 0x7f010059
			public const int subtitle = 2130772057;
			
			// aapt resource value: 0x7f01000f
			public const int subtitleTextStyle = 2130771983;
			
			// aapt resource value: 0x7f01002a
			public const int textAppearanceLargePopupMenu = 2130772010;
			
			// aapt resource value: 0x7f010043
			public const int textAppearanceListItemSmall = 2130772035;
			
			// aapt resource value: 0x7f01003f
			public const int textAppearanceSearchResultSubtitle = 2130772031;
			
			// aapt resource value: 0x7f01003e
			public const int textAppearanceSearchResultTitle = 2130772030;
			
			// aapt resource value: 0x7f01002c
			public const int textAppearanceSmall = 2130772012;
			
			// aapt resource value: 0x7f01002b
			public const int textAppearanceSmallPopupMenu = 2130772011;
			
			// aapt resource value: 0x7f01002d
			public const int textColorPrimary = 2130772013;
			
			// aapt resource value: 0x7f01002e
			public const int textColorPrimaryDisableOnly = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int textColorPrimaryInverse = 2130772015;
			
			// aapt resource value: 0x7f01003c
			public const int textColorSearchUrl = 2130772028;
			
			// aapt resource value: 0x7f010058
			public const int title = 2130772056;
			
			// aapt resource value: 0x7f01000e
			public const int titleTextStyle = 2130771982;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f01006f
			public const int ttf = 2130772079;
			
			// aapt resource value: 0x7f010065
			public const int verticalDivider = 2130772069;
			
			// aapt resource value: 0x7f010071
			public const int vertical_spacing = 2130772081;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			// aapt resource value: 0x7f01004f
			public const int windowActionBar = 2130772047;
			
			// aapt resource value: 0x7f010050
			public const int windowActionBarOverlay = 2130772048;
			
			// aapt resource value: 0x7f010051
			public const int windowActionModeOverlay = 2130772049;
			
			// aapt resource value: 0x7f010068
			public const int windowAnimationStyle = 2130772072;
			
			// aapt resource value: 0x7f010029
			public const int windowContentOverlay = 2130772009;
			
			// aapt resource value: 0x7f010044
			public const int windowMinWidthMajor = 2130772036;
			
			// aapt resource value: 0x7f010045
			public const int windowMinWidthMinor = 2130772037;
			
			// aapt resource value: 0x7f01004e
			public const int windowNoTitle = 2130772046;
			
			// aapt resource value: 0x7f010052
			public const int windowSplitActionBar = 2130772050;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int abs__action_bar_embed_tabs = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int abs__action_bar_expanded_action_views_exclusive = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int abs__config_actionMenuItemAllCaps = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int abs__config_allowActionMenuItemTextWithIcon = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int abs__config_showMenuShortcutsWhenKeyboardPresent = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int abs__split_action_bar_is_narrow = 2131099649;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int abs__background_holo_dark = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int abs__background_holo_light = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int abs__bright_foreground_disabled_holo_dark = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int abs__bright_foreground_disabled_holo_light = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int abs__bright_foreground_holo_dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int abs__bright_foreground_holo_light = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int abs__bright_foreground_inverse_holo_dark = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int abs__bright_foreground_inverse_holo_light = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int abs__holo_blue_light = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int abs__primary_text_disable_only_holo_dark = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int abs__primary_text_disable_only_holo_light = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int abs__primary_text_holo_dark = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int abs__primary_text_holo_light = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int black = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int blue = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int green = 2131165194;
			
			// aapt resource value: 0x7f070012
			public const int metro_button_text_style = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int red = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int white = 2131165196;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080013
			public const int SlidingMenuListPadding = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int SlidingMenuShadowWidth = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int SlidingmenuOffset = 2131230737;
			
			// aapt resource value: 0x7f080001
			public const int abs__action_bar_default_height = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int abs__action_bar_icon_vertical_padding = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int abs__action_bar_subtitle_bottom_margin = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int abs__action_bar_subtitle_text_size = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int abs__action_bar_subtitle_top_margin = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int abs__action_bar_title_text_size = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int abs__action_button_min_width = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int abs__alert_dialog_title_height = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int abs__config_prefDialogWidth = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int abs__dialog_min_width_major = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int abs__dialog_min_width_minor = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int abs__dropdownitem_icon_width = 2131230733;
			
			// aapt resource value: 0x7f08000b
			public const int abs__dropdownitem_text_padding_left = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int abs__dropdownitem_text_padding_right = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int abs__search_view_preferred_width = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int abs__search_view_text_min_width = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int action_button_min_width = 2131230736;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abs__ab_bottom_solid_dark_holo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int abs__ab_bottom_solid_inverse_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int abs__ab_bottom_solid_light_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int abs__ab_bottom_transparent_dark_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int abs__ab_bottom_transparent_light_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int abs__ab_share_pack_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int abs__ab_share_pack_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int abs__ab_solid_dark_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int abs__ab_solid_light_holo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int abs__ab_solid_shadow_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int abs__ab_stacked_solid_dark_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int abs__ab_stacked_solid_light_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int abs__ab_stacked_transparent_dark_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int abs__ab_stacked_transparent_light_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int abs__ab_transparent_dark_holo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int abs__ab_transparent_light_holo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int abs__activated_background_holo_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int abs__activated_background_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int abs__btn_cab_done_default_holo_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int abs__btn_cab_done_default_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int abs__btn_cab_done_focused_holo_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int abs__btn_cab_done_focused_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int abs__btn_cab_done_holo_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int abs__btn_cab_done_holo_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int abs__btn_cab_done_pressed_holo_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int abs__btn_cab_done_pressed_holo_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int abs__cab_background_bottom_holo_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int abs__cab_background_bottom_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int abs__cab_background_top_holo_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int abs__cab_background_top_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int abs__dialog_full_holo_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int abs__dialog_full_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int abs__ic_ab_back_holo_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int abs__ic_ab_back_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int abs__ic_cab_done_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int abs__ic_cab_done_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int abs__ic_clear = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int abs__ic_clear_disabled = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int abs__ic_clear_holo_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int abs__ic_clear_normal = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int abs__ic_clear_search_api_disabled_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int abs__ic_clear_search_api_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int abs__ic_go = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int abs__ic_go_search_api_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int abs__ic_menu_moreoverflow_holo_dark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int abs__ic_menu_moreoverflow_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int abs__ic_menu_moreoverflow_normal_holo_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int abs__ic_menu_moreoverflow_normal_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int abs__ic_menu_share_holo_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int abs__ic_menu_share_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int abs__ic_search = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int abs__ic_search_api_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int abs__ic_voice_search = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int abs__ic_voice_search_api_holo_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int abs__item_background_holo_dark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int abs__item_background_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int abs__list_activated_holo = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int abs__list_divider_holo_dark = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int abs__list_divider_holo_light = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int abs__list_focused_holo = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int abs__list_longpressed_holo = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int abs__list_pressed_holo_dark = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int abs__list_pressed_holo_light = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int abs__list_selector_background_transition_holo_dark = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int abs__list_selector_background_transition_holo_light = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int abs__list_selector_disabled_holo_dark = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int abs__list_selector_disabled_holo_light = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int abs__list_selector_holo_dark = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int abs__list_selector_holo_light = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int abs__menu_dropdown_panel_holo_dark = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int abs__menu_dropdown_panel_holo_light = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int abs__progress_bg_holo_dark = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int abs__progress_bg_holo_light = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int abs__progress_horizontal_holo_dark = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int abs__progress_horizontal_holo_light = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int abs__progress_medium_holo = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int abs__progress_primary_holo_dark = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int abs__progress_primary_holo_light = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int abs__progress_secondary_holo_dark = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int abs__progress_secondary_holo_light = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int abs__search_dropdown_dark = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int abs__search_dropdown_light = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int abs__spinner_48_inner_holo = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int abs__spinner_48_outer_holo = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int abs__spinner_ab_default_holo_dark = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int abs__spinner_ab_default_holo_light = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int abs__spinner_ab_disabled_holo_dark = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int abs__spinner_ab_disabled_holo_light = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int abs__spinner_ab_focused_holo_dark = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int abs__spinner_ab_focused_holo_light = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int abs__spinner_ab_holo_dark = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int abs__spinner_ab_holo_light = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int abs__spinner_ab_pressed_holo_dark = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int abs__spinner_ab_pressed_holo_light = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int abs__tab_indicator_ab_holo = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int abs__tab_selected_focused_holo = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int abs__tab_selected_holo = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int abs__tab_selected_pressed_holo = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int abs__tab_unselected_pressed_holo = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int abs__textfield_search_default_holo_dark = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int abs__textfield_search_default_holo_light = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int abs__textfield_search_right_default_holo_dark = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int abs__textfield_search_right_default_holo_light = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int abs__textfield_search_right_selected_holo_dark = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int abs__textfield_search_right_selected_holo_light = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int abs__textfield_search_selected_holo_dark = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int abs__textfield_search_selected_holo_light = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int abs__textfield_searchview_holo_dark = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int abs__textfield_searchview_holo_light = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int abs__textfield_searchview_right_holo_dark = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int abs__textfield_searchview_right_holo_light = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int allscripture = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int bearingwitness = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int bible = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int biblestories = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int bibleteach = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int closetojehovah = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int dailytext = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int godslove = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int greek = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int hebrew = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int ic_menu_archive = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int ic_menu_refresh = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int ic_menu_search = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int ic_menu_star = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int Icon = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int Icon_old = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int insight = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int isaiah1 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int isaiah2 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int james = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int jehovahsday = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int jehovahswill = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int jeremiah = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int kingdomcome = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int knowjehovah = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int knowledge = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int metro_button_style = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int ministryschool = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int myfollower = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int pubs = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int reasoning = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int revelation = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int search = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int singtojehovah = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int SlidingMenuShadow = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int Splash = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int tab_indicator = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int teacher = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int webview_border = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int worshipgod = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int youngpeople1 = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int youngpeople2 = 2130837656;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050049
			public const int ColorFrame = 2131034185;
			
			// aapt resource value: 0x7f05004b
			public const int ContentFrame = 2131034187;
			
			// aapt resource value: 0x7f050051
			public const int FragmentContainer = 2131034193;
			
			// aapt resource value: 0x7f050067
			public const int MenuFrame = 2131034215;
			
			// aapt resource value: 0x7f050068
			public const int MenuFrameSecondary = 2131034216;
			
			// aapt resource value: 0x7f05007d
			public const int TabIcon = 2131034237;
			
			// aapt resource value: 0x7f05007e
			public const int TabTitle = 2131034238;
			
			// aapt resource value: 0x7f050028
			public const int abs__action_bar = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int abs__action_bar_container = 2131034151;
			
			// aapt resource value: 0x7f050017
			public const int abs__action_bar_subtitle = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int abs__action_bar_title = 2131034134;
			
			// aapt resource value: 0x7f050029
			public const int abs__action_context_bar = 2131034153;
			
			// aapt resource value: 0x7f050011
			public const int abs__action_menu_divider = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int abs__action_menu_presenter = 2131034130;
			
			// aapt resource value: 0x7f05002c
			public const int abs__action_mode_bar = 2131034156;
			
			// aapt resource value: 0x7f05002b
			public const int abs__action_mode_bar_stub = 2131034155;
			
			// aapt resource value: 0x7f05001a
			public const int abs__action_mode_close_button = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int abs__activity_chooser_view_content = 2131034139;
			
			// aapt resource value: 0x7f050024
			public const int abs__checkbox = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int abs__content = 2131034147;
			
			// aapt resource value: 0x7f05001e
			public const int abs__default_activity_button = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int abs__expand_activities_button = 2131034140;
			
			// aapt resource value: 0x7f05000f
			public const int abs__home = 2131034127;
			
			// aapt resource value: 0x7f050020
			public const int abs__icon = 2131034144;
			
			// aapt resource value: 0x7f05001d
			public const int abs__image = 2131034141;
			
			// aapt resource value: 0x7f050018
			public const int abs__imageButton = 2131034136;
			
			// aapt resource value: 0x7f05001f
			public const int abs__list_item = 2131034143;
			
			// aapt resource value: 0x7f050013
			public const int abs__progress_circular = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int abs__progress_horizontal = 2131034132;
			
			// aapt resource value: 0x7f050026
			public const int abs__radio = 2131034150;
			
			// aapt resource value: 0x7f05002f
			public const int abs__search_badge = 2131034159;
			
			// aapt resource value: 0x7f05002e
			public const int abs__search_bar = 2131034158;
			
			// aapt resource value: 0x7f050030
			public const int abs__search_button = 2131034160;
			
			// aapt resource value: 0x7f050035
			public const int abs__search_close_btn = 2131034165;
			
			// aapt resource value: 0x7f050031
			public const int abs__search_edit_frame = 2131034161;
			
			// aapt resource value: 0x7f050037
			public const int abs__search_go_btn = 2131034167;
			
			// aapt resource value: 0x7f050032
			public const int abs__search_mag_icon = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int abs__search_plate = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int abs__search_src_text = 2131034164;
			
			// aapt resource value: 0x7f050038
			public const int abs__search_voice_btn = 2131034168;
			
			// aapt resource value: 0x7f050025
			public const int abs__shortcut = 2131034149;
			
			// aapt resource value: 0x7f05002a
			public const int abs__split_action_bar = 2131034154;
			
			// aapt resource value: 0x7f050036
			public const int abs__submit_area = 2131034166;
			
			// aapt resource value: 0x7f050019
			public const int abs__textButton = 2131034137;
			
			// aapt resource value: 0x7f050021
			public const int abs__title = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int abs__titleDivider = 2131034146;
			
			// aapt resource value: 0x7f050010
			public const int abs__up = 2131034128;
			
			// aapt resource value: 0x7f050045
			public const int asset_grid = 2131034181;
			
			// aapt resource value: 0x7f050015
			public const int auto_fit = 2131034133;
			
			// aapt resource value: 0x7f050040
			public const int bibleBookListItem = 2131034176;
			
			// aapt resource value: 0x7f05006c
			public const int body = 2131034220;
			
			// aapt resource value: 0x7f050042
			public const int bookDetailsItem = 2131034178;
			
			// aapt resource value: 0x7f050041
			public const int bookTitleItem = 2131034177;
			
			// aapt resource value: 0x7f05004a
			public const int button1 = 2131034186;
			
			// aapt resource value: 0x7f050048
			public const int chapterTitleItem = 2131034184;
			
			// aapt resource value: 0x7f050047
			public const int chaptersGridView = 2131034183;
			
			// aapt resource value: 0x7f050046
			public const int chaptersTitle = 2131034182;
			
			// aapt resource value: 0x7f05006d
			public const int confirm = 2131034221;
			
			// aapt resource value: 0x7f05000e
			public const int disableHome = 2131034126;
			
			// aapt resource value: 0x7f05004e
			public const int dtContent = 2131034190;
			
			// aapt resource value: 0x7f05004c
			public const int dtDate = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int dtScripture = 2131034189;
			
			// aapt resource value: 0x7f05002d
			public const int edit_query = 2131034157;
			
			// aapt resource value: 0x7f050058
			public const int fragmentContainer = 2131034200;
			
			// aapt resource value: 0x7f050003
			public const int fullscreen = 2131034115;
			
			// aapt resource value: 0x7f050057
			public const int gotoConfirm = 2131034199;
			
			// aapt resource value: 0x7f05003f
			public const int greekBibleBooks = 2131034175;
			
			// aapt resource value: 0x7f05003d
			public const int greekBibleContainer = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int greekBibleTitle = 2131034174;
			
			// aapt resource value: 0x7f050065
			public const int gridview2 = 2131034213;
			
			// aapt resource value: 0x7f05007a
			public const int headerText = 2131034234;
			
			// aapt resource value: 0x7f05003c
			public const int hebrewBibleBooks = 2131034172;
			
			// aapt resource value: 0x7f05003a
			public const int hebrewBibleContainer = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int hebrewBibleTitle = 2131034171;
			
			// aapt resource value: 0x7f050081
			public const int highlight = 2131034241;
			
			// aapt resource value: 0x7f05000b
			public const int homeAsUp = 2131034123;
			
			// aapt resource value: 0x7f05005a
			public const int htmlWebView = 2131034202;
			
			// aapt resource value: 0x7f050059
			public const int htmltextbox = 2131034201;
			
			// aapt resource value: 0x7f05007b
			public const int itemText = 2131034235;
			
			// aapt resource value: 0x7f050000
			public const int left = 2131034112;
			
			// aapt resource value: 0x7f050071
			public const int linearLayout1 = 2131034225;
			
			// aapt resource value: 0x7f050044
			public const int list = 2131034180;
			
			// aapt resource value: 0x7f050007
			public const int listMode = 2131034119;
			
			// aapt resource value: 0x7f050043
			public const int listView = 2131034179;
			
			// aapt resource value: 0x7f05005b
			public const int list_header_title = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int list_item_title = 2131034204;
			
			// aapt resource value: 0x7f050062
			public const int login = 2131034210;
			
			// aapt resource value: 0x7f050066
			public const int mainLayout = 2131034214;
			
			// aapt resource value: 0x7f050052
			public const int main_fragment = 2131034194;
			
			// aapt resource value: 0x7f050002
			public const int margin = 2131034114;
			
			// aapt resource value: 0x7f050039
			public const int navBibleBooks = 2131034169;
			
			// aapt resource value: 0x7f050006
			public const int normal = 2131034118;
			
			// aapt resource value: 0x7f050080
			public const int pagertab = 2131034240;
			
			// aapt resource value: 0x7f050060
			public const int password = 2131034208;
			
			// aapt resource value: 0x7f050063
			public const int pubImageItem = 2131034211;
			
			// aapt resource value: 0x7f050064
			public const int pubTitleItem = 2131034212;
			
			// aapt resource value: 0x7f05004f
			public const int readerWebView = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int readerWebView2 = 2131034192;
			
			// aapt resource value: 0x7f050053
			public const int realtabcontent = 2131034195;
			
			// aapt resource value: 0x7f050076
			public const int resultsProgressBar = 2131034230;
			
			// aapt resource value: 0x7f050001
			public const int right = 2131034113;
			
			// aapt resource value: 0x7f05006a
			public const int scriptureTextContent = 2131034218;
			
			// aapt resource value: 0x7f050069
			public const int scriptureTitle = 2131034217;
			
			// aapt resource value: 0x7f050082
			public const int search = 2131034242;
			
			// aapt resource value: 0x7f050075
			public const int searchButton = 2131034229;
			
			// aapt resource value: 0x7f050073
			public const int searchQuery = 2131034227;
			
			// aapt resource value: 0x7f050077
			public const int searchResults = 2131034231;
			
			// aapt resource value: 0x7f050074
			public const int searchSpinner = 2131034228;
			
			// aapt resource value: 0x7f050004
			public const int selected_view = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int showCustom = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int showHome = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int showTitle = 2131034124;
			
			// aapt resource value: 0x7f050061
			public const int signup = 2131034209;
			
			// aapt resource value: 0x7f05007c
			public const int slidingmenumain = 2131034236;
			
			// aapt resource value: 0x7f050054
			public const int spinnerB = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int spinnerC = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int spinnerV = 2131034198;
			
			// aapt resource value: 0x7f050008
			public const int tabMode = 2131034120;
			
			// aapt resource value: 0x7f050070
			public const int textNoteContent = 2131034224;
			
			// aapt resource value: 0x7f05006f
			public const int textNoteScriptureTitle = 2131034223;
			
			// aapt resource value: 0x7f05006e
			public const int textNoteTitle = 2131034222;
			
			// aapt resource value: 0x7f050079
			public const int textSearchContent = 2131034233;
			
			// aapt resource value: 0x7f050078
			public const int textSearchTitle = 2131034232;
			
			// aapt resource value: 0x7f050072
			public const int textView1 = 2131034226;
			
			// aapt resource value: 0x7f05006b
			public const int title = 2131034219;
			
			// aapt resource value: 0x7f05005f
			public const int txtpassword = 2131034207;
			
			// aapt resource value: 0x7f05005d
			public const int txtusername = 2131034205;
			
			// aapt resource value: 0x7f050009
			public const int useLogo = 2131034121;
			
			// aapt resource value: 0x7f05005e
			public const int username = 2131034206;
			
			// aapt resource value: 0x7f05007f
			public const int viewpager = 2131034239;
			
			// aapt resource value: 0x7f050005
			public const int wrap_content = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int abs__max_action_buttons = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int abs__action_bar_home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int abs__action_bar_tab = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int abs__action_bar_tab_bar_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int abs__action_bar_title_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int abs__action_menu_item_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int abs__action_menu_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int abs__action_mode_bar = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int abs__action_mode_close_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int abs__activity_chooser_view = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int abs__activity_chooser_view_list_item = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int abs__dialog_title_holo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int abs__list_menu_item_checkbox = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int abs__list_menu_item_icon = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int abs__list_menu_item_layout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int abs__list_menu_item_radio = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int abs__popup_menu_item_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int abs__screen_action_bar = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int abs__screen_action_bar_overlay = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int abs__screen_simple = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int abs__screen_simple_overlay_action_mode = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int abs__search_dropdown_item_icons_2line = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int abs__search_view = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int abs__simple_dropdown_hint = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int BibleBookGridFragment = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int BibleBooksListLayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Canon = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int CanonFragment = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int CanonGrid = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Chapters = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int ChapterSpinnerListLayout = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int ColorFrame = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int ContentFrame = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int DailyText = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int DuelReader = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int FragmentContainer = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int FragmentTabHost = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int GoToFragment = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int GridHeader = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int GridItem = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int Home = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int HTMLTextBox = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int HTMLWebView = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int List = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int ListHeader = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int ListItem = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int LogIn = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int MagazineItem = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int Magazines = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int Main = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int MainFragmentsContainer = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int MenuFrame = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int MenuFrameSecondary = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int NoteEdit = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int NoteRow = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int NotesList = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int PreferencesLayout = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int PublicationGridLayout = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int Publications = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int Reader = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int SearchFragment = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int SearchRow = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int SectionHeader = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int SectionItem = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int SectionItem_old = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int sherlock_spinner_dropdown_item = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int sherlock_spinner_item = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int slidingmenumain = 2130903106;
			
			// aapt resource value: 0x7f030043
			public const int TabIndicator = 2130903107;
			
			// aapt resource value: 0x7f030044
			public const int TabIndicator2 = 2130903108;
			
			// aapt resource value: 0x7f030045
			public const int ViewPagerLayout = 2130903109;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0d0000
			public const int highlighting_menu = 2131558400;
			
			// aapt resource value: 0x7f0d0001
			public const int search_options_menu = 2131558401;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a000f
			public const int ApplicationName = 2131361807;
			
			// aapt resource value: 0x7f0a0000
			public const int abs__action_bar_home_description = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int abs__action_bar_up_description = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int abs__action_menu_overflow_description = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int abs__action_mode_done = 2131361795;
			
			// aapt resource value: 0x7f0a0005
			public const int abs__activity_chooser_view_dialog_title_default = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int abs__activity_chooser_view_see_all = 2131361796;
			
			// aapt resource value: 0x7f0a0007
			public const int abs__activitychooserview_choose_application = 2131361799;
			
			// aapt resource value: 0x7f0a000c
			public const int abs__searchview_description_clear = 2131361804;
			
			// aapt resource value: 0x7f0a000b
			public const int abs__searchview_description_query = 2131361803;
			
			// aapt resource value: 0x7f0a000a
			public const int abs__searchview_description_search = 2131361802;
			
			// aapt resource value: 0x7f0a000d
			public const int abs__searchview_description_submit = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int abs__searchview_description_voice = 2131361806;
			
			// aapt resource value: 0x7f0a0006
			public const int abs__share_action_provider_share_with = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int abs__shareactionprovider_share_with = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int abs__shareactionprovider_share_with_application = 2131361801;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b005d
			public const int ActionBar_Solid = 2131427421;
			
			// aapt resource value: 0x7f0b005c
			public const int ActionBar_SubTitle = 2131427420;
			
			// aapt resource value: 0x7f0b005b
			public const int ActionBar_Title = 2131427419;
			
			// aapt resource value: 0x7f0b0036
			public const int DialogWindowTitle_Sherlock = 2131427382;
			
			// aapt resource value: 0x7f0b0037
			public const int DialogWindowTitle_Sherlock_Light = 2131427383;
			
			// aapt resource value: 0x7f0b004a
			public const int Sherlock___TextAppearance_Small = 2131427402;
			
			// aapt resource value: 0x7f0b004e
			public const int Sherlock___Theme = 2131427406;
			
			// aapt resource value: 0x7f0b0050
			public const int Sherlock___Theme_DarkActionBar = 2131427408;
			
			// aapt resource value: 0x7f0b0051
			public const int Sherlock___Theme_Dialog = 2131427409;
			
			// aapt resource value: 0x7f0b004f
			public const int Sherlock___Theme_Light = 2131427407;
			
			// aapt resource value: 0x7f0b0001
			public const int Sherlock___Widget_ActionBar = 2131427329;
			
			// aapt resource value: 0x7f0b0016
			public const int Sherlock___Widget_ActionMode = 2131427350;
			
			// aapt resource value: 0x7f0b001e
			public const int Sherlock___Widget_ActivityChooserView = 2131427358;
			
			// aapt resource value: 0x7f0b0029
			public const int Sherlock___Widget_Holo_DropDownItem = 2131427369;
			
			// aapt resource value: 0x7f0b0026
			public const int Sherlock___Widget_Holo_ListView = 2131427366;
			
			// aapt resource value: 0x7f0b0023
			public const int Sherlock___Widget_Holo_Spinner = 2131427363;
			
			// aapt resource value: 0x7f0b0033
			public const int Sherlock___Widget_SearchAutoCompleteTextView = 2131427379;
			
			// aapt resource value: 0x7f0b0048
			public const int TextAppearance_Sherlock_DialogWindowTitle = 2131427400;
			
			// aapt resource value: 0x7f0b0049
			public const int TextAppearance_Sherlock_Light_DialogWindowTitle = 2131427401;
			
			// aapt resource value: 0x7f0b004c
			public const int TextAppearance_Sherlock_Light_Small = 2131427404;
			
			// aapt resource value: 0x7f0b0043
			public const int TextAppearance_Sherlock_Light_Widget_PopupMenu_Large = 2131427395;
			
			// aapt resource value: 0x7f0b0045
			public const int TextAppearance_Sherlock_Light_Widget_PopupMenu_Small = 2131427397;
			
			// aapt resource value: 0x7f0b004b
			public const int TextAppearance_Sherlock_Small = 2131427403;
			
			// aapt resource value: 0x7f0b0038
			public const int TextAppearance_Sherlock_Widget_ActionBar_Menu = 2131427384;
			
			// aapt resource value: 0x7f0b003b
			public const int TextAppearance_Sherlock_Widget_ActionBar_Subtitle = 2131427387;
			
			// aapt resource value: 0x7f0b003c
			public const int TextAppearance_Sherlock_Widget_ActionBar_Subtitle_Inverse = 2131427388;
			
			// aapt resource value: 0x7f0b0039
			public const int TextAppearance_Sherlock_Widget_ActionBar_Title = 2131427385;
			
			// aapt resource value: 0x7f0b003a
			public const int TextAppearance_Sherlock_Widget_ActionBar_Title_Inverse = 2131427386;
			
			// aapt resource value: 0x7f0b003f
			public const int TextAppearance_Sherlock_Widget_ActionMode_Subtitle = 2131427391;
			
			// aapt resource value: 0x7f0b0040
			public const int TextAppearance_Sherlock_Widget_ActionMode_Subtitle_Inverse = 2131427392;
			
			// aapt resource value: 0x7f0b003d
			public const int TextAppearance_Sherlock_Widget_ActionMode_Title = 2131427389;
			
			// aapt resource value: 0x7f0b003e
			public const int TextAppearance_Sherlock_Widget_ActionMode_Title_Inverse = 2131427390;
			
			// aapt resource value: 0x7f0b004d
			public const int TextAppearance_Sherlock_Widget_DropDownHint = 2131427405;
			
			// aapt resource value: 0x7f0b0047
			public const int TextAppearance_Sherlock_Widget_DropDownItem = 2131427399;
			
			// aapt resource value: 0x7f0b0041
			public const int TextAppearance_Sherlock_Widget_PopupMenu = 2131427393;
			
			// aapt resource value: 0x7f0b0042
			public const int TextAppearance_Sherlock_Widget_PopupMenu_Large = 2131427394;
			
			// aapt resource value: 0x7f0b0044
			public const int TextAppearance_Sherlock_Widget_PopupMenu_Small = 2131427396;
			
			// aapt resource value: 0x7f0b0046
			public const int TextAppearance_Sherlock_Widget_TextView_SpinnerItem = 2131427398;
			
			// aapt resource value: 0x7f0b005a
			public const int Theme_MyApplications = 2131427418;
			
			// aapt resource value: 0x7f0b0052
			public const int Theme_Sherlock = 2131427410;
			
			// aapt resource value: 0x7f0b0057
			public const int Theme_Sherlock_Dialog = 2131427415;
			
			// aapt resource value: 0x7f0b0053
			public const int Theme_Sherlock_Light = 2131427411;
			
			// aapt resource value: 0x7f0b0054
			public const int Theme_Sherlock_Light_DarkActionBar = 2131427412;
			
			// aapt resource value: 0x7f0b0058
			public const int Theme_Sherlock_Light_Dialog = 2131427416;
			
			// aapt resource value: 0x7f0b0056
			public const int Theme_Sherlock_Light_NoActionBar = 2131427414;
			
			// aapt resource value: 0x7f0b0055
			public const int Theme_Sherlock_NoActionBar = 2131427413;
			
			// aapt resource value: 0x7f0b0059
			public const int Theme_Splash = 2131427417;
			
			// aapt resource value: 0x7f0b0000
			public const int Widget = 2131427328;
			
			// aapt resource value: 0x7f0b0002
			public const int Widget_Sherlock_ActionBar = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int Widget_Sherlock_ActionBar_Solid = 2131427331;
			
			// aapt resource value: 0x7f0b000a
			public const int Widget_Sherlock_ActionBar_TabBar = 2131427338;
			
			// aapt resource value: 0x7f0b000d
			public const int Widget_Sherlock_ActionBar_TabText = 2131427341;
			
			// aapt resource value: 0x7f0b0007
			public const int Widget_Sherlock_ActionBar_TabView = 2131427335;
			
			// aapt resource value: 0x7f0b0010
			public const int Widget_Sherlock_ActionButton = 2131427344;
			
			// aapt resource value: 0x7f0b0012
			public const int Widget_Sherlock_ActionButton_CloseMode = 2131427346;
			
			// aapt resource value: 0x7f0b0014
			public const int Widget_Sherlock_ActionButton_Overflow = 2131427348;
			
			// aapt resource value: 0x7f0b0017
			public const int Widget_Sherlock_ActionMode = 2131427351;
			
			// aapt resource value: 0x7f0b001f
			public const int Widget_Sherlock_ActivityChooserView = 2131427359;
			
			// aapt resource value: 0x7f0b0021
			public const int Widget_Sherlock_Button_Small = 2131427361;
			
			// aapt resource value: 0x7f0b002a
			public const int Widget_Sherlock_DropDownItem_Spinner = 2131427370;
			
			// aapt resource value: 0x7f0b0004
			public const int Widget_Sherlock_Light_ActionBar = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int Widget_Sherlock_Light_ActionBar_Solid = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int Widget_Sherlock_Light_ActionBar_Solid_Inverse = 2131427334;
			
			// aapt resource value: 0x7f0b000b
			public const int Widget_Sherlock_Light_ActionBar_TabBar = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int Widget_Sherlock_Light_ActionBar_TabBar_Inverse = 2131427340;
			
			// aapt resource value: 0x7f0b000e
			public const int Widget_Sherlock_Light_ActionBar_TabText = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int Widget_Sherlock_Light_ActionBar_TabText_Inverse = 2131427343;
			
			// aapt resource value: 0x7f0b0008
			public const int Widget_Sherlock_Light_ActionBar_TabView = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int Widget_Sherlock_Light_ActionBar_TabView_Inverse = 2131427337;
			
			// aapt resource value: 0x7f0b0011
			public const int Widget_Sherlock_Light_ActionButton = 2131427345;
			
			// aapt resource value: 0x7f0b0013
			public const int Widget_Sherlock_Light_ActionButton_CloseMode = 2131427347;
			
			// aapt resource value: 0x7f0b0015
			public const int Widget_Sherlock_Light_ActionButton_Overflow = 2131427349;
			
			// aapt resource value: 0x7f0b0018
			public const int Widget_Sherlock_Light_ActionMode = 2131427352;
			
			// aapt resource value: 0x7f0b0019
			public const int Widget_Sherlock_Light_ActionMode_Inverse = 2131427353;
			
			// aapt resource value: 0x7f0b0020
			public const int Widget_Sherlock_Light_ActivityChooserView = 2131427360;
			
			// aapt resource value: 0x7f0b0022
			public const int Widget_Sherlock_Light_Button_Small = 2131427362;
			
			// aapt resource value: 0x7f0b002b
			public const int Widget_Sherlock_Light_DropDownItem_Spinner = 2131427371;
			
			// aapt resource value: 0x7f0b001b
			public const int Widget_Sherlock_Light_ListPopupWindow = 2131427355;
			
			// aapt resource value: 0x7f0b0028
			public const int Widget_Sherlock_Light_ListView_DropDown = 2131427368;
			
			// aapt resource value: 0x7f0b001d
			public const int Widget_Sherlock_Light_PopupMenu = 2131427357;
			
			// aapt resource value: 0x7f0b002d
			public const int Widget_Sherlock_Light_PopupWindow_ActionMode = 2131427373;
			
			// aapt resource value: 0x7f0b002f
			public const int Widget_Sherlock_Light_ProgressBar = 2131427375;
			
			// aapt resource value: 0x7f0b0031
			public const int Widget_Sherlock_Light_ProgressBar_Horizontal = 2131427377;
			
			// aapt resource value: 0x7f0b0035
			public const int Widget_Sherlock_Light_SearchAutoCompleteTextView = 2131427381;
			
			// aapt resource value: 0x7f0b0025
			public const int Widget_Sherlock_Light_Spinner_DropDown_ActionBar = 2131427365;
			
			// aapt resource value: 0x7f0b001a
			public const int Widget_Sherlock_ListPopupWindow = 2131427354;
			
			// aapt resource value: 0x7f0b0027
			public const int Widget_Sherlock_ListView_DropDown = 2131427367;
			
			// aapt resource value: 0x7f0b001c
			public const int Widget_Sherlock_PopupMenu = 2131427356;
			
			// aapt resource value: 0x7f0b002c
			public const int Widget_Sherlock_PopupWindow_ActionMode = 2131427372;
			
			// aapt resource value: 0x7f0b002e
			public const int Widget_Sherlock_ProgressBar = 2131427374;
			
			// aapt resource value: 0x7f0b0030
			public const int Widget_Sherlock_ProgressBar_Horizontal = 2131427376;
			
			// aapt resource value: 0x7f0b0034
			public const int Widget_Sherlock_SearchAutoCompleteTextView = 2131427380;
			
			// aapt resource value: 0x7f0b0024
			public const int Widget_Sherlock_Spinner_DropDown_ActionBar = 2131427364;
			
			// aapt resource value: 0x7f0b0032
			public const int Widget_Sherlock_TextView_SpinnerItem = 2131427378;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] IonTextView = new int[] {
					2130772079};
			
			// aapt resource value: 0
			public const int IonTextView_ttf = 0;
			
			public static int[] LibraryGridView = new int[] {
					2130772080,
					2130772081,
					2130772082,
					2130772083};
			
			// aapt resource value: 3
			public const int LibraryGridView_column_count = 3;
			
			// aapt resource value: 2
			public const int LibraryGridView_column_width = 2;
			
			// aapt resource value: 0
			public const int LibraryGridView_horizontal_spacing = 0;
			
			// aapt resource value: 1
			public const int LibraryGridView_vertical_spacing = 1;
			
			public static int[] SherlockActionBar = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130772054,
					2130772055,
					2130772056,
					2130772057,
					2130772058,
					2130772059,
					2130772060,
					2130772061,
					2130772062,
					2130772063,
					2130772064,
					2130772065,
					2130772066};
			
			// aapt resource value: 2
			public const int SherlockActionBar_background = 2;
			
			// aapt resource value: 3
			public const int SherlockActionBar_backgroundSplit = 3;
			
			// aapt resource value: 12
			public const int SherlockActionBar_backgroundStacked = 12;
			
			// aapt resource value: 13
			public const int SherlockActionBar_customNavigationLayout = 13;
			
			// aapt resource value: 7
			public const int SherlockActionBar_displayOptions = 7;
			
			// aapt resource value: 5
			public const int SherlockActionBar_divider = 5;
			
			// aapt resource value: 4
			public const int SherlockActionBar_height = 4;
			
			// aapt resource value: 14
			public const int SherlockActionBar_homeLayout = 14;
			
			// aapt resource value: 10
			public const int SherlockActionBar_icon = 10;
			
			// aapt resource value: 16
			public const int SherlockActionBar_indeterminateProgressStyle = 16;
			
			// aapt resource value: 18
			public const int SherlockActionBar_itemPadding = 18;
			
			// aapt resource value: 11
			public const int SherlockActionBar_logo = 11;
			
			// aapt resource value: 6
			public const int SherlockActionBar_navigationMode = 6;
			
			// aapt resource value: 17
			public const int SherlockActionBar_progressBarPadding = 17;
			
			// aapt resource value: 15
			public const int SherlockActionBar_progressBarStyle = 15;
			
			// aapt resource value: 9
			public const int SherlockActionBar_subtitle = 9;
			
			// aapt resource value: 1
			public const int SherlockActionBar_subtitleTextStyle = 1;
			
			// aapt resource value: 8
			public const int SherlockActionBar_title = 8;
			
			// aapt resource value: 0
			public const int SherlockActionBar_titleTextStyle = 0;
			
			public static int[] SherlockActionMenuItemView = new int[] {
					16843071};
			
			// aapt resource value: 0
			public const int SherlockActionMenuItemView_android_minWidth = 0;
			
			public static int[] SherlockActionMode = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 2
			public const int SherlockActionMode_background = 2;
			
			// aapt resource value: 3
			public const int SherlockActionMode_backgroundSplit = 3;
			
			// aapt resource value: 4
			public const int SherlockActionMode_height = 4;
			
			// aapt resource value: 1
			public const int SherlockActionMode_subtitleTextStyle = 1;
			
			// aapt resource value: 0
			public const int SherlockActionMode_titleTextStyle = 0;
			
			public static int[] SherlockActivityChooserView = new int[] {
					16842964,
					2130772075,
					2130772076};
			
			// aapt resource value: 0
			public const int SherlockActivityChooserView_android_background = 0;
			
			// aapt resource value: 2
			public const int SherlockActivityChooserView_expandActivityOverflowButtonDrawable = 2;
			
			// aapt resource value: 1
			public const int SherlockActivityChooserView_initialActivityCount = 1;
			
			public static int[] SherlockMenuGroup = new int[] {
					16842766,
					16842960,
					16843156,
					16843230,
					16843231,
					16843232};
			
			// aapt resource value: 5
			public const int SherlockMenuGroup_android_checkableBehavior = 5;
			
			// aapt resource value: 0
			public const int SherlockMenuGroup_android_enabled = 0;
			
			// aapt resource value: 1
			public const int SherlockMenuGroup_android_id = 1;
			
			// aapt resource value: 3
			public const int SherlockMenuGroup_android_menuCategory = 3;
			
			// aapt resource value: 4
			public const int SherlockMenuGroup_android_orderInCategory = 4;
			
			// aapt resource value: 2
			public const int SherlockMenuGroup_android_visible = 2;
			
			public static int[] SherlockMenuItem = new int[] {
					16842754,
					16842766,
					16842960,
					16843014,
					16843156,
					16843230,
					16843231,
					16843233,
					16843234,
					16843235,
					16843236,
					16843237,
					16843375,
					16843481,
					16843515,
					16843516,
					16843657};
			
			// aapt resource value: 14
			public const int SherlockMenuItem_android_actionLayout = 14;
			
			// aapt resource value: 16
			public const int SherlockMenuItem_android_actionProviderClass = 16;
			
			// aapt resource value: 15
			public const int SherlockMenuItem_android_actionViewClass = 15;
			
			// aapt resource value: 9
			public const int SherlockMenuItem_android_alphabeticShortcut = 9;
			
			// aapt resource value: 11
			public const int SherlockMenuItem_android_checkable = 11;
			
			// aapt resource value: 3
			public const int SherlockMenuItem_android_checked = 3;
			
			// aapt resource value: 1
			public const int SherlockMenuItem_android_enabled = 1;
			
			// aapt resource value: 0
			public const int SherlockMenuItem_android_icon = 0;
			
			// aapt resource value: 2
			public const int SherlockMenuItem_android_id = 2;
			
			// aapt resource value: 5
			public const int SherlockMenuItem_android_menuCategory = 5;
			
			// aapt resource value: 10
			public const int SherlockMenuItem_android_numericShortcut = 10;
			
			// aapt resource value: 12
			public const int SherlockMenuItem_android_onClick = 12;
			
			// aapt resource value: 6
			public const int SherlockMenuItem_android_orderInCategory = 6;
			
			// aapt resource value: 13
			public const int SherlockMenuItem_android_showAsAction = 13;
			
			// aapt resource value: 7
			public const int SherlockMenuItem_android_title = 7;
			
			// aapt resource value: 8
			public const int SherlockMenuItem_android_titleCondensed = 8;
			
			// aapt resource value: 4
			public const int SherlockMenuItem_android_visible = 4;
			
			public static int[] SherlockMenuView = new int[] {
					2130772067,
					2130772068,
					2130772069,
					2130772070,
					2130772071,
					2130772072,
					2130772073,
					2130772074};
			
			// aapt resource value: 3
			public const int SherlockMenuView_headerBackground = 3;
			
			// aapt resource value: 1
			public const int SherlockMenuView_horizontalDivider = 1;
			
			// aapt resource value: 4
			public const int SherlockMenuView_itemBackground = 4;
			
			// aapt resource value: 6
			public const int SherlockMenuView_itemIconDisabledAlpha = 6;
			
			// aapt resource value: 0
			public const int SherlockMenuView_itemTextAppearance = 0;
			
			// aapt resource value: 7
			public const int SherlockMenuView_preserveIconSpacing = 7;
			
			// aapt resource value: 2
			public const int SherlockMenuView_verticalDivider = 2;
			
			// aapt resource value: 5
			public const int SherlockMenuView_windowAnimationStyle = 5;
			
			public static int[] SherlockSearchView = new int[] {
					16843039,
					16843296,
					16843364,
					2130772077,
					2130772078};
			
			// aapt resource value: 2
			public const int SherlockSearchView_android_imeOptions = 2;
			
			// aapt resource value: 1
			public const int SherlockSearchView_android_inputType = 1;
			
			// aapt resource value: 0
			public const int SherlockSearchView_android_maxWidth = 0;
			
			// aapt resource value: 3
			public const int SherlockSearchView_iconifiedByDefault = 3;
			
			// aapt resource value: 4
			public const int SherlockSearchView_queryHint = 4;
			
			public static int[] SherlockSpinner = new int[] {
					16842927,
					16843125,
					16843126,
					16843131,
					16843362,
					16843436,
					16843437,
					16843834};
			
			// aapt resource value: 5
			public const int SherlockSpinner_android_dropDownHorizontalOffset = 5;
			
			// aapt resource value: 1
			public const int SherlockSpinner_android_dropDownSelector = 1;
			
			// aapt resource value: 6
			public const int SherlockSpinner_android_dropDownVerticalOffset = 6;
			
			// aapt resource value: 4
			public const int SherlockSpinner_android_dropDownWidth = 4;
			
			// aapt resource value: 0
			public const int SherlockSpinner_android_gravity = 0;
			
			// aapt resource value: 2
			public const int SherlockSpinner_android_popupBackground = 2;
			
			// aapt resource value: 7
			public const int SherlockSpinner_android_popupPromptView = 7;
			
			// aapt resource value: 3
			public const int SherlockSpinner_android_prompt = 3;
			
			public static int[] SherlockTheme = new int[] {
					16842839,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050,
					2130772051,
					2130772052,
					2130772053};
			
			// aapt resource value: 9
			public const int SherlockTheme_actionBarDivider = 9;
			
			// aapt resource value: 10
			public const int SherlockTheme_actionBarItemBackground = 10;
			
			// aapt resource value: 8
			public const int SherlockTheme_actionBarSize = 8;
			
			// aapt resource value: 6
			public const int SherlockTheme_actionBarSplitStyle = 6;
			
			// aapt resource value: 5
			public const int SherlockTheme_actionBarStyle = 5;
			
			// aapt resource value: 2
			public const int SherlockTheme_actionBarTabBarStyle = 2;
			
			// aapt resource value: 1
			public const int SherlockTheme_actionBarTabStyle = 1;
			
			// aapt resource value: 3
			public const int SherlockTheme_actionBarTabTextStyle = 3;
			
			// aapt resource value: 7
			public const int SherlockTheme_actionBarWidgetTheme = 7;
			
			// aapt resource value: 53
			public const int SherlockTheme_actionButtonStyle = 53;
			
			// aapt resource value: 52
			public const int SherlockTheme_actionDropDownStyle = 52;
			
			// aapt resource value: 11
			public const int SherlockTheme_actionMenuTextAppearance = 11;
			
			// aapt resource value: 12
			public const int SherlockTheme_actionMenuTextColor = 12;
			
			// aapt resource value: 15
			public const int SherlockTheme_actionModeBackground = 15;
			
			// aapt resource value: 14
			public const int SherlockTheme_actionModeCloseButtonStyle = 14;
			
			// aapt resource value: 17
			public const int SherlockTheme_actionModeCloseDrawable = 17;
			
			// aapt resource value: 19
			public const int SherlockTheme_actionModePopupWindowStyle = 19;
			
			// aapt resource value: 18
			public const int SherlockTheme_actionModeShareDrawable = 18;
			
			// aapt resource value: 16
			public const int SherlockTheme_actionModeSplitBackground = 16;
			
			// aapt resource value: 13
			public const int SherlockTheme_actionModeStyle = 13;
			
			// aapt resource value: 4
			public const int SherlockTheme_actionOverflowButtonStyle = 4;
			
			// aapt resource value: 58
			public const int SherlockTheme_actionSpinnerItemStyle = 58;
			
			// aapt resource value: 66
			public const int SherlockTheme_activatedBackgroundIndicator = 66;
			
			// aapt resource value: 65
			public const int SherlockTheme_activityChooserViewStyle = 65;
			
			// aapt resource value: 0
			public const int SherlockTheme_android_windowIsFloating = 0;
			
			// aapt resource value: 20
			public const int SherlockTheme_buttonStyleSmall = 20;
			
			// aapt resource value: 51
			public const int SherlockTheme_dividerVertical = 51;
			
			// aapt resource value: 55
			public const int SherlockTheme_dropDownListViewStyle = 55;
			
			// aapt resource value: 57
			public const int SherlockTheme_dropdownListPreferredItemHeight = 57;
			
			// aapt resource value: 54
			public const int SherlockTheme_homeAsUpIndicator = 54;
			
			// aapt resource value: 64
			public const int SherlockTheme_listPopupWindowStyle = 64;
			
			// aapt resource value: 45
			public const int SherlockTheme_listPreferredItemHeightSmall = 45;
			
			// aapt resource value: 46
			public const int SherlockTheme_listPreferredItemPaddingLeft = 46;
			
			// aapt resource value: 47
			public const int SherlockTheme_listPreferredItemPaddingRight = 47;
			
			// aapt resource value: 56
			public const int SherlockTheme_popupMenuStyle = 56;
			
			// aapt resource value: 31
			public const int SherlockTheme_searchAutoCompleteTextView = 31;
			
			// aapt resource value: 32
			public const int SherlockTheme_searchDropdownBackground = 32;
			
			// aapt resource value: 42
			public const int SherlockTheme_searchResultListItemHeight = 42;
			
			// aapt resource value: 33
			public const int SherlockTheme_searchViewCloseIcon = 33;
			
			// aapt resource value: 37
			public const int SherlockTheme_searchViewEditQuery = 37;
			
			// aapt resource value: 38
			public const int SherlockTheme_searchViewEditQueryBackground = 38;
			
			// aapt resource value: 34
			public const int SherlockTheme_searchViewGoIcon = 34;
			
			// aapt resource value: 35
			public const int SherlockTheme_searchViewSearchIcon = 35;
			
			// aapt resource value: 39
			public const int SherlockTheme_searchViewTextField = 39;
			
			// aapt resource value: 40
			public const int SherlockTheme_searchViewTextFieldRight = 40;
			
			// aapt resource value: 36
			public const int SherlockTheme_searchViewVoiceIcon = 36;
			
			// aapt resource value: 21
			public const int SherlockTheme_selectableItemBackground = 21;
			
			// aapt resource value: 30
			public const int SherlockTheme_spinnerDropDownItemStyle = 30;
			
			// aapt resource value: 29
			public const int SherlockTheme_spinnerItemStyle = 29;
			
			// aapt resource value: 23
			public const int SherlockTheme_textAppearanceLargePopupMenu = 23;
			
			// aapt resource value: 48
			public const int SherlockTheme_textAppearanceListItemSmall = 48;
			
			// aapt resource value: 44
			public const int SherlockTheme_textAppearanceSearchResultSubtitle = 44;
			
			// aapt resource value: 43
			public const int SherlockTheme_textAppearanceSearchResultTitle = 43;
			
			// aapt resource value: 25
			public const int SherlockTheme_textAppearanceSmall = 25;
			
			// aapt resource value: 24
			public const int SherlockTheme_textAppearanceSmallPopupMenu = 24;
			
			// aapt resource value: 26
			public const int SherlockTheme_textColorPrimary = 26;
			
			// aapt resource value: 27
			public const int SherlockTheme_textColorPrimaryDisableOnly = 27;
			
			// aapt resource value: 28
			public const int SherlockTheme_textColorPrimaryInverse = 28;
			
			// aapt resource value: 41
			public const int SherlockTheme_textColorSearchUrl = 41;
			
			// aapt resource value: 60
			public const int SherlockTheme_windowActionBar = 60;
			
			// aapt resource value: 61
			public const int SherlockTheme_windowActionBarOverlay = 61;
			
			// aapt resource value: 62
			public const int SherlockTheme_windowActionModeOverlay = 62;
			
			// aapt resource value: 22
			public const int SherlockTheme_windowContentOverlay = 22;
			
			// aapt resource value: 49
			public const int SherlockTheme_windowMinWidthMajor = 49;
			
			// aapt resource value: 50
			public const int SherlockTheme_windowMinWidthMinor = 50;
			
			// aapt resource value: 59
			public const int SherlockTheme_windowNoTitle = 59;
			
			// aapt resource value: 63
			public const int SherlockTheme_windowSplitActionBar = 63;
			
			public static int[] SherlockView = new int[] {
					16842970};
			
			// aapt resource value: 0
			public const int SherlockView_android_focusable = 0;
			
			public static int[] SlidingMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
