#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ActionsContentView.Resource", IsApplication=false)]

namespace ActionsContentView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public static int actions_layout = 2130771974;
			
			// aapt resource value: 0x7f010005
			public static int actions_spacing = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int content_layout = 2130771975;
			
			// aapt resource value: 0x7f01000d
			public static int effect_actions = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public static int effect_content = 2130771982;
			
			// aapt resource value: 0x7f010002
			public static int effects = 2130771970;
			
			// aapt resource value: 0x7f01000f
			public static int effects_interpolator = 2130771983;
			
			// aapt resource value: 0x7f01000a
			public static int fade_max_value = 2130771978;
			
			// aapt resource value: 0x7f010001
			public static int fade_type = 2130771969;
			
			// aapt resource value: 0x7f01000b
			public static int fling_duration = 2130771979;
			
			// aapt resource value: 0x7f010008
			public static int shadow_drawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int shadow_width = 2130771977;
			
			// aapt resource value: 0x7f010004
			public static int spacing = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int spacing_type = 2130771968;
			
			// aapt resource value: 0x7f01000c
			public static int swiping_edge_width = 2130771980;
			
			// aapt resource value: 0x7f010003
			public static int swiping_type = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f020001
			public static int default_actionscontentview_actions_spacing = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int default_actionscontentview_spacing = 2130837504;
			
			// aapt resource value: 0x7f020002
			public static int default_actionscontentview_swiping_edge_width = 2130837506;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public static int actions = 2130968578;
			
			// aapt resource value: 0x7f040000
			public static int actions_width = 2130968576;
			
			// aapt resource value: 0x7f040006
			public static int all = 2130968582;
			
			// aapt resource value: 0x7f040003
			public static int both = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int content = 2130968580;
			
			// aapt resource value: 0x7f04000d
			public static int edge = 2130968589;
			
			// aapt resource value: 0x7f040007
			public static int fling = 2130968583;
			
			// aapt resource value: 0x7f040008
			public static int fling_closing = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int fling_opening = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public static int full = 2130968590;
			
			// aapt resource value: 0x7f040005
			public static int none = 2130968581;
			
			// aapt resource value: 0x7f040001
			public static int right_offset = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public static int scroll = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int scroll_closing = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public static int scroll_opening = 2130968588;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f030000
			public static int default_actionscontentview_fade_max_value = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int default_actionscontentview_fling_duration = 2130903041;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionsContentView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 6
			public static int ActionsContentView_actions_layout = 6;
			
			// aapt resource value: 5
			public static int ActionsContentView_actions_spacing = 5;
			
			// aapt resource value: 7
			public static int ActionsContentView_content_layout = 7;
			
			// aapt resource value: 13
			public static int ActionsContentView_effect_actions = 13;
			
			// aapt resource value: 14
			public static int ActionsContentView_effect_content = 14;
			
			// aapt resource value: 2
			public static int ActionsContentView_effects = 2;
			
			// aapt resource value: 15
			public static int ActionsContentView_effects_interpolator = 15;
			
			// aapt resource value: 10
			public static int ActionsContentView_fade_max_value = 10;
			
			// aapt resource value: 1
			public static int ActionsContentView_fade_type = 1;
			
			// aapt resource value: 11
			public static int ActionsContentView_fling_duration = 11;
			
			// aapt resource value: 8
			public static int ActionsContentView_shadow_drawable = 8;
			
			// aapt resource value: 9
			public static int ActionsContentView_shadow_width = 9;
			
			// aapt resource value: 4
			public static int ActionsContentView_spacing = 4;
			
			// aapt resource value: 0
			public static int ActionsContentView_spacing_type = 0;
			
			// aapt resource value: 12
			public static int ActionsContentView_swiping_edge_width = 12;
			
			// aapt resource value: 3
			public static int ActionsContentView_swiping_type = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
